# Generated by Django 3.0.6 on 2021-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
            ],
            options={
                'db_table': 'Bank',
            },
        ),
    ]
