# Generated by Django 3.0.6 on 2021-08-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quizClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.IntegerField()),
                ('que', models.CharField(max_length=200)),
                ('opta', models.CharField(max_length=200)),
                ('optb', models.CharField(max_length=200)),
                ('optc', models.CharField(max_length=200)),
                ('optd', models.CharField(max_length=200)),
                ('rightans', models.IntegerField()),
            ],
            options={
                'db_table': 'questions1',
            },
        ),
    ]
