# Generated by Django 3.0.6 on 2021-08-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiztest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quizclass',
            table='questions',
        ),
    ]
